#ifndef RESOURCE_H
#define RESOURCE_H

#define IDR_MAINMENU 101
#define IDM_EXIT 102
#define IDM_POINT 103
#define IDM_LINE 104
#define IDM_RECTANGLE 105
#define IDM_ELLIPSE 106
#define IDM_ABOUT 107
#define IDD_ABOUTBOX 108

#define IDC_STATIC -1
#define IDC_TOOLBAR 109
#define ID_TOOL_POINT 110
#define ID_TOOL_LINE 111
#define ID_TOOL_RECTANGLE 112
#define ID_TOOL_ELLIPSE 113

#endif // RESOURCE_H
